NOAA-OWP/cfe

src/bmi_cfe.c, src/main.c
Need to ensure any variables used in computation have some initial value before they are used in any operation.
* Initial values for variables that were using bad memory
- `flux_perc_m`
- `volin`
* For good practice, initialize a few other variables to 0.0
* Fix bug in main driver as well
1. Ran several iterations with consistent, non earth ending output values.
=> Bug fix 31

include/bmi_cfe.h, src/bmi_cfe.c
In the case that Update_until is used and a fractional timestep is run, need to attempt to scale the input to match the time framction.
- Add `time_step_fraction` in cfe_state_struct
- Use `time_step_fraction` in `Update` to scale input prior to running CFE
=> Track fractional time and adjust input accordingly

include/cfe.h, src/bmi_cfe.c, src/cfe.c
`evap_struct` [type-def'ed ](https://github.com/NOAA-OWP/cfe/blob/023b794f599e48984e5f2f99f70cdfcc82e3f29b/include/cfe.h#L207 ) as 
```
struct evapotranspiration_structure {
double potential_et_m_per_s;
double potential_et_m_per_timestep;
double actual_et_m_per_timestep;
};
``` 
is fully [initialized](https://github.com/NOAA-OWP/cfe/blob/92f253654494d810115d1d37d97607128a159903/src/bmi_cfe.c#L953) and [set/updated](https://github.com/NOAA-OWP/cfe/blob/92f253654494d810115d1d37d97607128a159903/src/cfe.c#L79) (assigned value) for all members, including now `potential_et_m_per_timestep`.  
This is needed for subroutine functions [`et_from_rainfall`](https://github.com/NOAA-OWP/cfe/blob/023b794f599e48984e5f2f99f70cdfcc82e3f29b/src/cfe.c#L666) & …
=> Valid use of `evap_struct` (for all members)

include/bmi.h, src/bmi_cfe.c, test/main_unit_test_bmi.c, test_serialize/cfe_serialize_test.c, test_serialize/serialize_state.c
Appling minor changes to owp-bmi-enhancements; mostly to match topmodel code
- Add function [`get_model_roles()`](https://github.com/madMatchstick/cfe/blob/786737181796782245d12b8603a951b59c0a720c/src/bmi_cfe.c#L1163) & role listing (17) [array](https://github.com/madMatchstick/cfe/blob/786737181796782245d12b8603a951b59c0a720c/src/bmi_cfe.c#L149)
- All [instances](https://github.com/madMatchstick/cfe/blob/786737181796782245d12b8603a951b59c0a720c/src/bmi_cfe.c#L241) of input and ouput variable arrays and `#DEFINE` sizes unneeded, replaced by `var_info`
- Removed `get_adusted_index_for_variable()` [function](https://github.com/madMatchstick/cfe/blob/786737181796782245d12b8603a951b59c0a720c/src/bmi_cfe.c#L1136) as I don't think it's really needed - other than to check if the variable name …
=> fine tune bmi enhancements to match tmod

src/bmi_cfe.c
Tweaks to CFE BMI to allow setting calibration parameters after model initialization, using existing BMI functionality
-  `param_var_names`, `param_var_types`
-
- Add params to `Get_adjusted_index_for_variable`, `Get_var_type`, `Get_value_ptr`
1. Tested via ngen build which sets param values after initialization (and via calibration loop execution)
- A few comments/notes left in the code disscussion side effecting parameters and considerations for a couple other bmi functions.
=> allow bmi to set calibration parameters

src/bmi_cfe.c, src/cfe.c
Adds Potential and Actual ET to bmi Output so we can test on ngen. For now, the standard names were not used since we cannot have variables with same names as output and input. We might want to change that in the future (including the other output variables). 
Add two additional variables to bmi output: potential and actual evapotranspiration
Nothing was removed. 
-
1. Tested with ./make_and_run_bmi_pass_forcings_pet.sh and in ngen
-
-
- [x ] PR has an informative and human-readable title
- [ x] Changes are limited to a single goal (no scope creep)
- [ x] Code can be automatically merged (no conflicts)
- [ x] Passes all existing automated tests
- [ x] Any _change_ in functionality is tested
=> Adding ET to output

test/main_unit_test_bmi.c
Simply tests `get_value()` and `set_value()` functions for newly added parameter variables (not input nor output).
Closes #54 
- In[ bmi unit testing](https://github.com/NOAA-OWP/cfe/blob/4c8f6a8022ef243c00bd7a843e50d9f37b884a19/test/main_unit_test_bmi.c#L390), call get and set values for all 10 parameters and confirm values match. 
1. make_and_run_bmi_unit_test.sh
=> incl params g/set value in bmi unit testing

README.md, configs/cat_87_bmi_config_cfe_pass.txt, src/bmi_cfe.c, src/cfe.c
[Short description explaining the high-level reason for the pull request]
- logic block in Xinanjiang routine to work when parameters are zero.  Assumes 95% runoff in these cases.
- description of gw_storage and soil_storage in config file cat_87_bmi_config_cfe_pass
- fixed initial groundwater storage_m and soil water storage_m from [m/m] to [m] by multiplying the decimal fraction provided in the config file by the max storage in their respective reservoirs.
1. Passes mass balance checks when the parameters (smcmax and/or soil_storage) are set to zero (catchment 87). Expected change can be seen in runoff
2. Passes mass balance checks with original parameter set (catchment 87)
Original parameter set
smcmax set to zero
-
-
=> XAJ zero params and initial storage_m bug fixes

src/bmi_cfe.c
The bmi initialization code leaks the file handle from the `fopen` call.  Especially in the ngen case where this be initialized many times, this leads to an exhaustion of open file handles on the system can cause it to crash.  Fixes #67.
- Close the file handle after reading of file is complete
1. Tested with ngen
=> close initialization file after reading to avoid resource leak

src/bmi_cfe.c
A potential overflow bug exists in the `read_file_line_counts` function.  Depending on system, compiler, and hardware, this can lead to a infinite loop.
- Change the i/o buffer type for character reading to `int` from `char` to avoid overflowing a possible unsigned char type.
1. Tested through ngen unit tests
=> fix potential overflow that can lead to infinite loop in file reading

configs/realization_cfe_pet.json
Added a local nextgen realization file, a comparable example file of cfe with `FORCINGPET` pseudo-framework test. This allows us to directly compare the CFE pseudo-framework and ngen results.
- no additions to the code
- no removals
- no changes
=> added_realization_file

README.md, configs/realization_cfe_pet.json, include/cfe.h, include/conceptual_reservoir.h, src/bmi_cfe.c, src/cfe.c
The PR changes bmi input variable name from `ice_fraction_xinan` to `ice_fraction_xinanjiang` to make it more descriptive and consistent with SoilFreezeThaw output name.
- None
- None
- BMI input variable name change
1. All existing tests pass (include pseudo and nextgen tests)
=> changed_bmi_name

src/bmi_cfe.c
Affected line is allocating `(sizeof(double) * num_giuh_ordinates) + 1` bytes instead of `sizeof(double) * (num_giuh_ordinates + 1)` bytes, causing a heap buffer overflow in the following loop.
i.e. https://github.com/NOAA-OWP/ngen/actions/runs/7388585995/job/20099716766?pr=694
- Adds parenthesis around `num_giuh_ordinates + 1`.
=> Fix allocation size for runoff_queue_m_per_timestep

.github/workflows/ngen_integration.yaml, realizations/realization_cfe_pet_ngenCI.json
This PR removes the re-checkout block of codes in the original `ngen_integration.yaml` so the code is cleaner. Also, the CFE shared library build is updated to be consistent with CFE update.
-
-
.github/workflows/ngen_integration.yaml
realizations/realization_cfe_pet_ngenCI.json
Passed all automated tests.
-
-
=> Remove re-checkout

configs/README.md, configs/laramie_bmi_config_cfe_pass_aet_rz.txt, include/conceptual_reservoir.h, src/bmi_cfe.c, src/cfe.c
The PR fixes bugs when using the AET Root Zone option. Currently, the rootzone block in the `et_from_soil` (in cfe.c) does not execute as `aet_rootzone` flag is always `OFF`. Other minor name changes..
- None
- None
- name changes: `sft_coupled` to `is_sft_coupled` and `aet_rootzone` to `is_aet_rootzone`, also names with `root_zone` changed to `rootzone` (no underscore) for consistency
1. tested the code to make sure the aet_rootzone option is used correctly
- This bug was found while reviewing PR [104](https://github.com/NOAA-OWP/cfe/pull/104)
=> bug_fix_aet rootzone

src/bmi_cfe.c
In support of NOAA-OWP/ngen#718, CFE needs to build without warnings in that setting.
- Check the return values of the few `fgets()` calls in input reading.
1. Local build no longer warns
2. CI
=> Support building with `-Werror` for ngen

.github/workflows/ngen_integration.yaml, CMakeLists.txt
We want to ensure code quality issues get caught relatively early, before they cause problems in ngen integration tests on updates.
- Enable AddressSanitizer (ASan)
- Build with `-Werror` (including `-Og` to get control/data-flow analysis for necessary warnings)
- Stop smashing CMake options that the user may have set on the command line
1. CI
=> Tighten CI checks

.github/workflows/Build_and_Run_Standalone_Test.yml
Includes 4th pseudo-framework option (`AETROOTZONE`) to standalone workflow test.  Closes issue #109.
=> add aetrootzone option to workflow

configs/README.md, configs/cat_87_bmi_config_cfe.txt, configs/cat_87_bmi_config_cfe_pass.txt, configs/cat_87_config_cfe_pass_surfnash.txt, configs/cat_89_bmi_config_cfe_unit_test.txt, configs/laramie_bmi_config_cfe_pass_aet_rz.txt, src/bmi_cfe.c
The PR addresses backward compatibility issue related to config file parameter `surface_runoff_scheme` that arose in the PR #112. The default option for surface_runoff_scheme is set to `GIUH`. Reverted config files and added a new BMI variable NASH_RUNOFF.  Note: this PR is not to be mixed with PR #116. 
- Added a new BMI variable NASH_RUNOFF
- None
- No changes to the functionality
1. All tests results are consistent with pre-changes results
=> backwards_compibility_changes

realizations/realization_cfe_pet_surfnash.json, src/bmi_cfe.c, test/main_unit_test.c
The PR adds a new parameter `retention_depth_surface_nash` to the calibratable parameters list per Fred's request.
- added a calibratable parameter
- None
- None
1. All existing tests passed
=> Added retention_depth to calibrated params

src/bmi_cfe.c, src/main_cfe_aorc_pet_rz_aet.cxx
The PR fixes issue #93 - make the `Set_value` and `Set_value_at_indices` functions consistent with the BMI 2.0 standard. No Changes to the functionality of the model
- Modified `Set_value` and `Set_value_at_indices` functions
- None
- None
1. All existing tests passed, and results are unchanged
2. Manually tested calibratable parameters using ngen realization.json to ensure they are working properly
=> adjusted_BMI_set_get_functions

configs/README.md, src/bmi_cfe.c
The PR fixed issues created via git issues. These changes don't change the functionality of the model.
1. closed #58  -- fixed RAIN_RATE units
2. closed #69 -- new units are in `m`
3. closed #124 (updated docs)
4. closed #125 (fixed missing units warnings)
- None
- None
- No changes to the functionality
1. All existing tests passed
=> fixed_several_issues

configs/cfe1.0/cfe_config_laramie_pass_aet_rz.txt, configs/cfe_config_laramie_pass_aet_rz.txt, src/bmi_cfe.c
VERY minor updates left over from PR #105.  `is_aet_rootzone` (boolean flag) name changed for consistency but was ever fully adopted in bmi spec & configs. 
- `aet_rootzone` now reads `is_aet_rootzone`
1. All workflows pass
=> Aet rootzone name fix

configs/README.md, include/bmi_cfe.h, realizations/realization_cfe_pet_surfgiuh.json, realizations/realization_cfe_pet_surfnash.json, src/bmi_cfe.c
The PR adds `NWM_PONDED_DEPTH` variable to the BMI variables output list. It represents surface water, stored in the GIUH/NASH_Cascade array, that didn't drain during the current timestep. It will be need for NextGen vars parity with NWM variables.
- Added a BMI output variable
- None
- None
1. All existing tests pass and results are unchanged
=> Added_NWM_ponded depth

include/cfe.h, src/bmi_cfe.c, src/cfe.c
Replacing #142 with cleaned up commits and more importantly tries to prevent the segfault seen in the tests on that PR by
1. Setting `nash_storage` to a NULL pointer when using GIUH surface routing.
2. Checking if `nash_storage == NULL` prior to computing AET from the nash retention depth.
=> Fix aet, replaces #142
